### ISSUE TITLE
Continuous  delivery

### ISSUE THREAD

**Issue by enniomara** [enniomara/shortify#7]
On merge, run `terraform apply` so that it deploys automatically

**Comment by chrillebile** [comment]
By using terraform cloud you could do this very easily;
https://learn.hashicorp.com/tutorials/terraform/github-actions

**Comment by enniomara** [comment]
I think that tutorial is for using terraform cloud as state backend together with Github Actions. As shortify stores the state on AWS, I don't think terraform cloud is needed.

**Comment by enniomara** [comment]
Making this possible would mean creating a 'production' account and running deploying shortify there. The terraform docs contain some info on how mulit-account works with regards to using S3+DynamoDB as storage backend. 

https://www.terraform.io/docs/language/settings/backends/s3.html#multi-account-aws-architecture

**Comment by enniomara** [comment]
Different accounts can be managed via AWS Organizations[0], where each environment would ideally have one account (e.g. shortify-prod, shortify-stage). These environments can be achieved in a single account, but it will most likely be pain to handle iam permissions for the different environments. I've already created an account for prod, just need to figure out how to delegate access based on roles. 

https://console.aws.amazon.com/organizations/v2/
